### ISSUE TITLE
More than two levels of hierarchy in a collected work

### ISSUE THREAD

**Issue by khanson679** [lingbib/lingbib#12]
Related to #5, I think there may be other cases where it's unclear how to deal with multi-part works.

It may be that in such cases, the bottom level work is simply split into multiple physical volumes due to sheer size, hopefully with unified page numbering, and can thus the smallest logical unit can be cited without regard for its physical format.

However, I wouldn't be surprised if we encounter true multi-level works eventually. So even if we leave this open or consult the working group (regard how to print such data), I thought I'd bring it up now.

Biblatex has a `part` field, which is states is for books only. I'll use this in some sketches of how we might do this.

Ex. 1: a multi-part journal issue.
- journal (`xdata`)
  - volume X (n/a)
    - issue Y (`xdata`, volume=X, number=Y)
      - part Z (`xdata`, ?field=Z)
        - `article`

Ex. 2: perhaps more likely, a multi-part volume in a collection. 
- `mvcollection`
  - volume X (`xdata`, volume=X)
    - part Y (`xdata`, part(??)=Y)
      - self-contained work (`incollection`)

Ex. 3: probably the least problematic
- `mvbook`
  - volume X (`xdata`, volume=X
    - subvolume Y (`book`, part(??)=Y)

**Comment by adamliter** [comment]
I'm not sure I understand what the question is here. What is a "true multi-level work" supposed to be? Is this just supposed to be something where it would be right to use Biblatex's `part` data field? Biblatex explicitly says that this field should not be used for journals (and, indeed, I'm not aware of any journals that publishes one volume in multiple parts).

I've never seen collections or books that have volumes split into multiple parts (except maybe there are separately labeled parts inside the TOC and the main matter of the book, but never multiple parts of the same volume in different physical books (at least not that I've seen)).

**Comment by khanson679** [comment]
That's fine if you don't think this will happen. In that case, it's all just hypothetical.

**Comment by adamliter** [comment]
Yeah, I'm really not aware of any instances of such a thing, but I suppose it's possible.

**Comment by khanson679** [comment]
It's interesting that Biblatex has this field though, and specifically says it's for when "a logical volume consists of two or more physical ones". This suggests that they, at least, think this is the more likely thing to happen.

Assuming this is correct, I'm thinking that the case of multiple physical volumes in a logical volume is one where we would do away with the extra entry. If the citable entry is for a `@book` (with unified page numbers), then the part might be irrelevant. If the citable entry is an `@inbook` or `@incollection`, then the `part` field can just go in the entry for the small unit. Does this sound good as a provisional plan?

**Comment by adamliter** [comment]
I'm not sure why it follows from Biblatex having the field that it's a likely thing to happen. I assume they just have the field because it does happen at least sometimes. I've never seen this happen in a linguistics publication, however.

But anyway, aside form that, yes, that sounds like a good provisional plan.

**Comment by khanson679** [comment]
Key word in that sentence: "the /more/ likely thing to happen". And okay.

**Comment by adamliter** [comment]
:stuck_out_tongue: Sorry, I must have misread it! :smile:
