### ISSUE TITLE
Are full dates of publication necessary for books and similar works?

### ISSUE THREAD

**Issue by khanson679** [lingbib/lingbib#9]
Often in existing databases only the year is given. Is this adequate? My intuition is that the full date is unnecessary for our purposes.

**Comment by adamliter** [comment]
I think it might be useful to at least get the month of publication, if we can. Sometimes I've seen conflicting information online as to which month a book was actually published in. If that's the case, then it's probably worth just leaving it at the year. However, if the month information is available, then I think it would be worth having, especially if there are any styles ought there that end-users might want/need to use in their work which rely on sorting the bibliography by date. Sorting can get dicey if you have prolific authors publishing a lot of stuff in the same year. What do you think?

**Comment by khanson679** [comment]
Of course, I agree that if the full info is available we should include it. That's a good point about multiple publications in the same year. (Hopefully we won't have to worry about multiple publications in the same month.)

The issue is when we can't find the full date, or if the sources conflict. What is to be the policy on this? I've only looked up one item so far, so I don't have a good feel for this.

**Comment by khanson679** [comment]
Here's the Chomsky KOL entry. http://www.worldcat.org/title/knowledge-of-language-its-nature-origin-and-use/oclc/12235328&referer=brief_results

I just don't know what to say when the world's premier (?) bibliographic database for books doesn't list the full date.

**Comment by adamliter** [comment]
I think if we have conflicting sources, then, if possible, we (i) defer to information directly from the publisher, but if the publisher doesn't give the full date (which often seems to be the case) and if, for example, Amazon and Google books have conflicting information about the publication date, then we should (ii) only enter the date to the extent that they agree. So if they agree on the month but not the date, then we could enter YYYY-MM. Or if they only agree on the year, then we would just enter YYYY. What do you think?

**Comment by khanson679** [comment]
So basically, give as much accurate information as we can, otherwise omit. I guess this is the only sensible approach.

**Comment by adamliter** [comment]
Yes, I think so too. Sounds like we are in agreement.
